### ISSUE TITLE
Improve logging in libhdbpp-cassandra

### ISSUE THREAD

**Issue by bourtemb** [tango-controls-hdbpp/libhdbpp-cassandra#4]
It would be useful to be able to configure the logging level of the HDB++ Cassandra library (and Cassandra driver logging level) via LibConfiguration Tango property used by the HDBEventSubscriber and HDBConfigurationManager device servers.

**Comment by chedburgh** [comment]
Fixed by merged branch. This changed updated the API and so the library version. This effected all componets (libhdbpp, libhdbpp-mysql, libhdbpp-mysql-legacy and libhdbpp-cassandra), and they must be updated together.
