### ISSUE TITLE
Use exceptions instead of returning error codes whenever possible

### ISSUE THREAD

**Issue by bourtemb** [tango-controls-hdbpp/libhdbpp-cassandra#5]
In the current version of HDB++ Event Subscriber and libhdb++cassandra library, a DB Storage error message is reported when there is a problem storing data into Cassandra, without more details about the error. Using exceptions in the library could help improving diagnostics for problems related to Cassandra storage.

**Comment by chedburgh** [comment]
Fixed by merged branch. This changed updated the API and so the library version. This effected all componets (libhdbpp, libhdbpp-mysql, libhdbpp-mysql-legacy and libhdbpp-cassandra), and they must be updated together.
